project_id = "yinswjhmcgftinrjsokv"

[functions.extract-property]
verify_jwt = false

[functions.chat-extract]
verify_jwt = false

[functions.approve-property]
verify_jwt = false

[functions.publish-property]
verify_jwt = false

[functions.form-submit]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.gmail-oauth]
verify_jwt = false

[functions.gmail-oauth-callback]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.sitemap]
verify_jwt = false


[functions.translate-content]
verify_jwt = false
